### ISSUE TITLE
testpmd Benchmark: trex-traffic pod fails due to json decode error

### ISSUE THREAD

**Issue by Tan2Pi** [cloud-bulldozer/benchmark-operator#583]
Testing DPDK with the TestPMD Benchmark using Mellanox NICs on an OCP 4.6 cluster. TestPMD pod comes up, but trex-traffic pod fails due to a JSON decode error:
```
[core@r190bcsah sriov-dpdk]$ oc logs -f trex-traffic-gen-pod-91b58ddd-qwrdq
2021-05-25T19:54:49Z - INFO     - MainProcess - run_snafu: logging level is INFO
2021-05-25T19:54:49Z - INFO     - MainProcess - wrapper_factory: identified trex as the benchmark wrapper
2021-05-25T19:54:49Z - INFO     - MainProcess - trigger_trex: Starting TRex Traffic Generator..
Traceback (most recent call last):
  File "/usr/local/bin/run_snafu", line 33, in <module>
    sys.exit(load_entry_point('snafu', 'console_scripts', 'run_snafu')())
  File "/opt/snafu/snafu/run_snafu.py", line 118, in main
    for i in process_generator(index_args, parser):
  File "/opt/snafu/snafu/run_snafu.py", line 138, in process_generator
    for action, index in data_object.emit_actions():
  File "/opt/snafu/snafu/trex_wrapper/trigger_trex.py", line 68, in emit_actions
    documents = self._json_payload(stdout)
  File "/opt/snafu/snafu/trex_wrapper/trigger_trex.py", line 33, in _json_payload
    payload = json.loads(data)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  
```  
Here is the benchmark CR used:  
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: testpmd-benchmark-mlx
  namespace: my-ripsaw
spec:
  clustername: ocp
  workload:
    name: testpmd
    args:
      privileged: true
      pin: true
      pin_testpmd: "<node-1>"
      pin_trex: "<node-1>"
      networks:
        testpmd:
          - name: mlx-dpdk-network
            count: 2  # Interface count, Min 2
        trex:
          - name: mlx-dpdk-network
            count: 2
```  

This benchmark completes successfully if I use an SriovNetwork that has Intel XXV710 NIC Vfs, but not with an SriovNetwork using Mellanox CX-4 Vfs. Let me know if any other debug info is needed.

**Comment by mukrishn** [comment]
@Tan2Pi PR in progress for MLNX cards.
https://github.com/cloud-bulldozer/benchmark-operator/pull/580 & https://github.com/cloud-bulldozer/benchmark-wrapper/pull/275/files

**Comment by mukrishn** [comment]
@Tan2Pi This is fixed already in the mentioned PR, can be closed if no more concerns.
